### ISSUE TITLE
Deb build attempt for bionic/18.04 fails with "The 'dbus-python' distribution was not found"

### ISSUE THREAD

**Issue by Halfwalker** [flaktack/systemd-resolved-docker#7]
Would very much like to use this with Ubuntu bionic/18.04 (because reasons), so attempting to manual-build following the steps in the `github/workflows/workflow.yml`.  Figuring the build process for 20.04 would be closest - that whole process works fine and a `python-systemd-resolved-docker_1.0.0_all.deb` is built and can be installed.

The problem shows up with the service not starting.  Running manually with `sudo /usr/bin/systemd-resolved-docker` results in

```
ubuntu@bionic:~/systemd-resolved-docker$ sudo /usr/bin/systemd-resolved-docker
Traceback (most recent call last):
  File "/usr/bin/systemd-resolved-docker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dbus-python' distribution was not found and is required by systemd-resolved-docker
```

**Comment by Halfwalker** [comment]
Note - default python3 is `3.6.9` on Ubuntu 18.04.  Updated to `3.8.16` from deadsnakes.  Same issue.
